apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: express-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-redis
  template:
    metadata:
      labels:
        app: express-redis
    spec:
      containers:
      - name: express-api-container
        image: express-api-container:0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lol-secret
              key: redisPassword
        - name: ENTRY_KEY
          valueFrom:
            configMapKeyRef:
              name: lol-configmap
              key: entryKey